sudo: required

services:
  - docker

notifications:
  email: false

before_deploy:
  - ./generate-pdf.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "tex/monografia.pdf"
  skip_cleanup: true
  overwrite: true
  on:
    repo: andreformento/tcc-monografia
    tags: true
