sudo: required

services:
  - docker

notifications:
  email: false

before_deploy:
  - ./generate-pdf.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "monografia.pdf"
  skip_cleanup: true
  on:
    tags: true
